

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ✅ Use Inter instead of Geist
import "./globals.css";
import { ThemeProvider } from "@/lib/Providers/next-theme-provider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    
    <body className={`${inter.variable} antialiased `}>
      {children}
    </body>

  </html>
  );
}
